services:
  agent:
    build: .
    # command: python main.py
    command: sleep infinity
    stdin_open: true
    tty: true
    container_name: agent
    env_file:
      - .env
    volumes:
      - ./agent:/llm/agent
      - ./providers:/llm/providers
      - ~/.kube/config:/root/.kube/config
      - ./main.py:/llm/main.py # FOR TESTING
      - ./data/logs:/var/log/agent
  
  executor:
    build: .
    command: python /app/server.py
    container_name: executor
    env_file:
      - .env
    volumes:
      - ./providers:/llm/providers
      - ~/.kube/config:/root/.kube/config
      - ./server.py:/app/server.py
    ports:
      - "8000:8000"

  # vector-db:
  #   image: qdrant/qdrant
  #   container_name: vector-db
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   environment:
  #     - QDRANT__SERVICE__GRPC_PORT=6334
  #   volumes:
  #     - ./data/qdrant:/qdrant/storage
