services:
  agent:
    build: .
    container_name: agent
    command: python main.py
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./agent:/llm/agent
      - ./providers:/llm/providers
      - ./main.py:/llm/main.py
      - ~/.kube/config:/root/.kube/config
      - ~/.aws:/root/.aws
      - ./data/logs:/var/log/agent

